- id: check-config
  name: Check prometheus config files
  description: Check prometheus config files
  entry: bin/check-config-wrapper.sh
  language: script
  pass_filenames: true
  types: ['file']
  verbose: true
  args:
  # prometheus docker tag, default latest
  - latest
- id: check-rules
  name: Check prometheus rule files
  description: Check prometheus rule files
  entry: bin/check-rules-wrapper.sh
  language: script
  pass_filenames: true
  types: ['file']
  verbose: true
  args:
  # prometheus docker tag, default latest
  - latest
