- id: check-config
  name: Check prometheus config files
  description: Check prometheus config files
  language: docker_image
  entry: --entrypoint /bin/promtool prom/prometheus:latest
  files: >
    (?x)^(
        ""
    )$
  args:
  - check
  - rules

- id: check-rules
  stages: [commit]
  name: Check prometheus rule files
  description: Check prometheus rule files
  language: docker_image
  entry: --entrypoint /bin/promtool prom/prometheus:latest
  files: >
    (?x)^(
        ""
    )$
  args:
  - check
  - rules
